In [1]:
import pandas as pd
import numpy as np

In [2]:
ethnea_df = pd.read_csv('names_ethnea_genni_country_sample.csv')

In [3]:
ethnea_df

AUID                              Last               First  \
0      12872768_1                           _Filho_     _Elias_Abdalla_   
1      12565879_3                    _Bou_Abdallah_               _Jad_   
2      17569133_1                      _Abdel_Aziz_             _Ayman_   
3      11213157_2                      _Abdelmoula_             _Salma_   
4      11439058_1                           _Abdou_           _Ibrahim_   
5      10919608_3                 _Abou_El_Fettouh_             _Hazem_   
6      17314740_3                        _Aboutaam_              _Rola_   
7      16564217_2  _Alvim_de_Abreu_Silva_Rodrigues_    _Aida_Alexandra_   
8       6339395_2      _Cristina_Affonso_Scaletsky_            _Isabel_   
9       7796089_2                       _Agbenyega_             _Tsiri_   
10      5473023_2             _Maria_Aguado_Garcia_              _Jose_   
11     15153355_4                 _Aguilar_Guisado_           _Manuela_   
12     11981185_4                   _Aguillon_Luna_            _Arturo_   
13     12554913_2                      _Ahmadzadeh_               _Ali_   
14     10066026_5                         _Ibrahim_             _Ahmed_   
15     17642770_2                         _Letaief_             _Ahmed_   
16     14766995_2                   _Shakeel_Ahmed_          _Mohammed_   
17     16343417_1                     _Aksoy_Dogan_              _Alev_   
18      3866040_3               _Nakatsukasa_Akune_           _Mitsumi_   
19     12663244_3                           _Akyuz_             _Filiz_   
20      2830628_1                       _Al_Gohary_           _Omaimah_   
21     12113661_3                        _Al_Jedah_            _Jassim_   
22      3104205_7                       _Al_Khatib_             _Shadi_   
23      7520609_3                       _Al_Najjar_              _Azmi_   
24       927746_1                     _Alba_Conejo_            _Emilio_   
25     18451155_4                         _Llaguno_  _Sheila_Alcantara_   
26      9431676_4                         _Alcocer_            _Marcos_   
27      3720520_1               _Grazia_Alessandri_             _Maria_   
28     10480445_2                       _Ali_Labib_             _Randa_   
29     12636048_1                  _Allie_Hamdulay_           _Shameez_   
...           ...                               ...                 ...   
44537  12641914_1                             _Liu_           _Zhihong_   
44538  16892144_4                             _Liu_         _Zhen_ying_   
44539  15566960_5                             _Liu_               _Zhu_   
44540  12828461_3                             _Liu_          _Zhengjie_   
44541  12726928_3                             _Liu_         _Zhengchun_   
44542  17802886_5                             _Liu_           _Ziliang_   
44543  18032929_3                             _Liu_               _Zhe_   
44544  16690641_1                             _Liu_            _Zulian_   
44545  17554931_2                             _Liu_          _Zun_chun_   
44546  18975769_5                             _Liu_           _Ze_zhou_   
44547  19458823_2                             _Liu_          _Zhaochun_   
44548   8734067_3                             _Liu_            _ziying_   
44549   9706530_4                             _Liu_            _zhenyu_   
44550   6068528_4                          _Tanaka_             _kenzo_   
44551    180046_3                          _Tanaka_            _kimiko_   
44552   1942669_3                          _Tanaka_          _kazuhiro_   
44553   9571188_3                          _Tanaka_              _koji_   
44554  11071249_4                          _Tanaka_            _Kousei_   
44555  12828613_4                          _Tanaka_             _Kyoko_   
44556  19073144_1                          _Tanaka_             _Kenji_   
44557   8449402_2                          _Tanaka_             _keiji_   
44558  10671491_5                     

In [45]:
#combine first_name and last_name
name_series = ethnea_df['Last'] + ethnea_df['First']
name_series = name_series.replace('_',' ',regex=True)
name_series = name_series.str.strip()
name_series = name_series.str.upper()

#extract ethnicity rows
ethnic_series = ethnea_df.Ethnea.values

In [46]:
#make a name vector from all the dataset
name_dict = {}
for i,name_i in enumerate(name_series.str.split(' ')):
    for name in name_i:
        if name != '':
            if name not in name_dict:
                name_dict[name] = []
            name_dict[name].append(ethnic_series[i])

In [47]:
len(name_dict)

34834

In [48]:
name_dict

{'FILHO': ['HISPANIC',
  'HISPANIC',
  'HISPANIC',
  'HISPANIC',
  'HISPANIC',
  'HISPANIC',
  'HISPANIC',
  'HISPANIC',
  'HISPANIC',
  'HISPANIC',
  'HISPANIC'],
 'ELIAS': ['HISPANIC',
  'HISPANIC',
  'HISPANIC',
  'ARAB',
  'ARAB',
  'ENGLISH',
  'HISPANIC',
  'HISPANIC',
  'HISPANIC',
  'GREEK'],
 'ABDALLA': ['HISPANIC', 'ARAB', 'ARAB', 'ARAB'],
 'BOU': ['ARAB'],
 'ABDALLAH': ['ARAB', 'ARAB', 'ARAB', 'FRENCH'],
 'JAD': ['ARAB'],
 'ABDEL': ['ARAB',
  'ARAB',
  'ARAB',
  'ARAB',
  'ARAB',
  'ARAB',
  'ARAB',
  'ARAB',
  'ARAB',
  'ARAB',
  'ARAB'],
 'AZIZ': ['ARAB', 'ARAB', 'ARAB', 'ARAB', 'ARAB'],
 'AYMAN': ['ARAB', 'ARAB'],
 'ABDELMOULA': ['ARAB', 'ARAB'],
 'SALMA': ['ARAB', 'ARAB'],
 'ABDOU': ['ARAB'],
 'IBRAHIM': ['ARAB',
  'ARAB',
  'ARAB',
  'ARAB',
  'ARAB',
  'ARAB',
  'AFRICAN',
  'AFRICAN',
  'ARAB',
  'ARAB',
  'ARAB',
  'ARAB',
  'ARAB',
  'ARAB',
  'ARAB',
  'TURKISH',
  'ARAB',
  'ARAB'],
 'ABOU': ['ARAB', 'ARAB', 'ARAB', 'ARAB', 'ARAB'],
 'EL': ['ARAB',
  'ARAB',
  'AR

In [8]:
# assume ethnic is a document
ethnic_dict = {}
for i,ethnic_i in enumerate(ethnic_list):
    if ethnic_i not in ethnic_dict:
        ethnic_dict[ethnic_i] = []
    # split the name
    split_name = name_series[i].split(' ')
    for name_j in split_name:
        if name_j!='':
            ethnic_dict[ethnic_i].append(name_j)

In [147]:
ethnic_list = list(ethnic_dict.keys())
name_list = list(name_dict.keys())

In [220]:
#calculate tf
# prepare tf-idf matrix
tf_idf = np.zeros( [len(name_dict),len(ethnic_dict)])
idf = np.zeros( len(name_dict) )
total_name_on_eth = np.zeros( len(ethnic_dict) ) 
for name,ethnic in name_dict.items():
    ethnic_tracer = []
    for ethnic_i in ethnic:
        if ethnic_i not in ethnic_tracer:
            idf[name_list.index(name)]+=1
            ethnic_tracer.append(ethnic_i)
        tf_idf[name_list.index(name),ethnic_list.index(ethnic_i)]+=1
        total_name_on_eth[ethnic_list.index(ethnic_i)]+=1
        #compute the tf and assign it to tf_idf
    idf[name_list.index(name)] = np.log(len(ethnic_list)/idf[name_list.index(name)])
    
# compute tf
for i,ethnic_i in enumerate(ethnic_list):
    tf_idf[:,i] = tf_idf[:,i] / total_name_on_eth[i]

    
# multiply with the idf
#for i,name_i in enumerate(name_list):
#    tf_idf[i,:] = tf_idf[i,:]*idf[i]

In [218]:
tf_idf

array([[ 0.00319149,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.00097115,  0.00114476,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.000226  ,  0.00239759,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [219]:
tf_idf[1].sum()

0.0044673990064121438

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [16]:
from sklearn.datasets import fetch_20newsgroups
dataset = fetch_20newsgroups(shuffle=True, random_state=1,
                             remove=('headers', 'footers', 'quotes'))

In [17]:
dataset.keys()

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR', 'description'])

In [28]:
data_tmp = []
for key in ethnic_list:
    data_tmp.append(" ".join(ethnic_dict[key]))

In [29]:
data_tmp

['FILHO ELIAS ABDALLA ALVIM DE ABREU SILVA RODRIGUES AIDA ALEXANDRA CRISTINA AFFONSO SCALETSKY ISABEL MARIA AGUADO GARCIA JOSE AGUILAR GUISADO MANUELA AGUILLON LUNA ARTURO ALBA CONEJO EMILIO LLAGUNO SHEILA ALCANTARA ALCOCER MARCOS MOREIRA ALMEIDA ALEXANDER LUIZ JESUS DE ALMEIDA JOSE SAMPAIO ALMEIDA MANUELLA ALONSO BEGONA LUIS ALONSO LEBRERO JOSE ALONSO MORAGA ANGELES GARCIA ALSINA JOAN ALVA ESPINOSA CARLOS ALVARADO ELVIRA FREITAS DE ALVARENGA KATIA ALVAREZ SANCHEZ VICTORIA ROCHA ALVAREZ ROSICLER ALVARO BLANCO JOSUE REGO PEREIRA VALERIA ALZATE LUIS FERNANDO AMANDIO VIEIRA ANGEL ROSELINA ANTOLIN JUAREZ FRANCISCO ANTONIO GARCIA VELA JOSE ARANDA FRAUSTRO ALBERTO ARANTES TIAGO EUGENIO STANISLAU DE ARAUJO EVALDO MARIA SAINZ ROSA ARCELUS MARTINEZ JUAN RAMIREZ DE ARELLANO ENCARNACION ARGENTONI BALDOCHI MEIRE ARGUELLO MORALES MARTHA MARIA ARIAS HERNANDEZ ROSA ARIAS ORTIZ JAVIER ARIZA CARDENAL CARLES ARREAZA LUISA GARCIA ARTERO ENRIQUE MONTES ATENAS GONZALO LARANJA GUSTAVO VEGA AVILA ELISA AYUSO

In [43]:
tfidf_vectorizer = TfidfVectorizer(max_df=0.95, min_df=2,
                                   max_features=23)
tfidf = tfidf_vectorizer.fit_transform(data_tmp)

In [44]:
tfidf.toarray()

array([[  0.00000000e+00,   4.25778711e-02,   4.97137784e-01,
          2.77758809e-03,   0.00000000e+00,   6.46623787e-01,
          2.77758809e-03,   0.00000000e+00,   5.63108675e-01,
          0.00000000e+00,   1.24991464e-01,   1.01845834e-02,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          2.62169805e-03,   0.00000000e+00,   8.86296494e-03,
          0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   1.86008800e-01

In [99]:
data_samples = name_series.values
n_features = 5000

# Use tf-idf features for NMF.
print("Extracting tf-idf features for NMF...")
tfidf_vectorizer = TfidfVectorizer(max_features=n_features)
name_vector = tfidf_vectorizer.fit_transform(data_samples)
name_vector = name_vector.toarray()

Extracting tf-idf features for NMF...


In [139]:
x = tfidf_vectorizer.transform(['Nikolaus Robert'])

In [140]:
np.where(x.toarray()>0)

(array([0, 0]), array([3293, 3771]))

In [143]:
name_dict['ROBERT']

['ENGLISH',
 'ENGLISH',
 'FRENCH',
 'ENGLISH',
 'ENGLISH',
 'GERMAN',
 'GERMAN',
 'SLAV',
 'NORDIC',
 'ENGLISH',
 'GERMAN',
 'GERMAN',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'GERMAN',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'GERMAN',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'SLAV',
 'SLAV',
 'GERMAN',
 'ENGLISH',
 'ENGLISH',
 'DUTCH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'ENGLISH',
 'GERMAN',
 'ENGLISH',
 'SLAV',
 'GERMAN',
 'ENGLISH',
 'DUTCH',
 'ENGLISH',
 'ENGLI

In [181]:
tf_idf[name_list.index('NIKOLAUS')]

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.00039339,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ])

In [183]:
#convert the first name and last name combine into a vector representing the ethnicity matrix
name_list_idf = []
for name_i in name_series:
    name_split = name_i.split(' ')
    y = np.ones(len(ethnic_list))
    for x in name_split:
        if x != '':
            y = y * tf_idf[name_list.index(x)]
    name_list_idf.append(y)


In [215]:
name_list_idf[5]

array([  0.00000000e+00,   3.78355926e-12,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00])

In [192]:
#ingest the vectors into logistic regression with ethnicity as the target class
from sklearn.linear_model import LogisticRegression
# need to do it later
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.99,
#                                                    random_state=42)

logreg = LogisticRegression()

# we create an instance of Neighbours Classifier and fit the data.
logreg.fit(name_list_idf, ethnic_series)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [213]:
logreg.predict_proba(name_list_idf[4])

/home/nnikolaus/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([[ 0.00419736,  0.03008017,  0.0011808 ,  0.09283617,  0.02059557,
         0.32296823,  0.05019679,  0.08265012,  0.00852504,  0.09648435,
         0.00408602,  0.03583119,  0.0004203 ,  0.0080338 ,  0.04135756,
         0.09903592,  0.01614561,  0.03263073,  0.00208603,  0.03341527,
         0.00450921,  0.01207715,  0.0006566 ]])

In [204]:
name_list_idf[0]

array([  5.22911847e-11,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00])

In [207]:
name_series[0] + ethnic_series[0]

'FILHO  ELIAS ABDALLAHISPANIC'